#ifndef DIALOGGEOMETRY_H
#define DIALOGGEOMETRY_H


#define MAIN_W_WIDTH 420
#define MAIN_W_HEIGTH 180

#define SERVER_DIALOG_WIDTH 400
#define SERVER_DIALOG_HEIGHT 400

#define CLIENT_DIALOG_WIDTH 400
#define CLIENT_DIALOG_HEIGHT 200

#endif // DIALOGGEOMETRY_H
